# Generated by Django 3.1.5 on 2021-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210127_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='na@na.com', max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(default=9999999999),
        ),
    ]
